### ISSUE TITLE
Publish to platformio registry

### ISSUE THREAD

**Issue by kfern** [mum4k/arduino_abstractions#12]
Hi @mum4k 

We can publish the library in the platformio registry. I'm going to make a pull request with minor changes to the library.json file.

A Platformio user account is required to manage packages in the registry

Can you create it?

https://docs.platformio.org/en/latest/plus/pio-account.html

**Comment by mum4k** [comment]
I appreciate the detailed instructions @kfern, I have just performed these steps.

**Comment by mum4k** [comment]
Looks like the first run failed, because the script was waiting for confirmation:

https://github.com/mum4k/arduino_abstractions/runs/4086821936?check_suite_focus=true

Is there a flag we can add to make it non-interactive?

**Comment by kfern** [comment]
Yes. I had not included the --non-interactive option

**Comment by mum4k** [comment]
Thank you for adding it.

**Comment by kfern** [comment]
Published https://platformio.org/lib/show/13008/Arduino%20Abstractions

**Comment by mum4k** [comment]
Awesome, thank you for your help here @kfern !
