### ISSUE TITLE
Next. RFC: Software Serial Abstraction

### ISSUE THREAD

**Issue by kfern** [mum4k/arduino_abstractions#9]
Hi @mum4k 

The [current SoftwareSerial interface](https://www.arduino.cc/en/Reference/SoftwareSerial) is completely different from this abstraction. 

"The version of SoftwareSerial included in 1.0 and later is based on the NewSoftSerial library by Mikal Hart."

What do we do?

**Comment by mum4k** [comment]
Hi @kfern, I think it is safe to conclude that the abstraction provided here is no longer useful. We can delete the current abstraction and optionally define one based on the new library. The abstractions included here were mostly meant as examples, so we can also leave it to others to implement the software serial abstraction once they need it.
